### ISSUE TITLE
.obt availability?

### ISSUE THREAD

**Issue by raz123** [dglava/arc-openbox#2]
> ObConf now easily installs new themes which use the .obt Openbox theme archive format for distribution. Just open any .obt theme archive in your file browser, or use the interface provided inside ObConf.
> 
> You can also use ObConf to create .obt Openbox theme archives for distributing your own themes. 

Source: http://openbox.org/wiki/ObConf:About

PS: lovely work!

**Comment by dglava** [comment]
Thanks for the suggestion. I added the OBT files, for those who prefer to install it automatically.
