### ISSUE TITLE
@AUR

### ISSUE THREAD

**Issue by patlux** [dglava/arc-openbox#3]
Thank you for this openbox theme!

I created a aur package for this:
https://aur.archlinux.org/packages/openbox-arc-git/

**via [pacaur](https://github.com/rmarquis/pacaur)**

``` bash
pacaur -S openbox-arc-git
```

**via [yaourt](https://github.com/archlinuxfr/yaourt)**

``` bash
yaourt -S openbox-arc-git
```

**[manual](https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_packages):**

``` bash
curl "https://aur.archlinux.org/cgit/aur.git/snapshot/openbox-arc-git.tar.gz" |tar xz
cd "openbox-arc-git"
makepkg -si
```

Have fun!

**Comment by dglava** [comment]
Thank you! I have updated the README to include a link to the AUR page.
