### ISSUE TITLE
Remove gtk-engine-murrine dependency

### ISSUE THREAD

**Issue by Brottweiler** [dglava/arc-openbox#6]
The [package](https://aur.archlinux.org/packages/openbox-arc-git/) in the AUR has a dependency for `gtk-engine-murrine`, but as [justasug](https://aur.archlinux.org/account/justasug) sais in the comments, your package does not depend on this. Only the original Arc theme packages does.

Since you don't seem to respond to the AUR package, I am posting this here.

**Comment by dglava** [comment]
This is a funny misunderstanding. I am not the AUR package maintainer, but I am the person (justasug) who pointed out the unnecessary dependency on the AUR page.  :)

Maybe you could try flagging it out-of-date to get the packager's attention or directly mailing him? If he abandoned the package, I think you can submit a request to take over it or I could do it.

**Comment by Brottweiler** [comment]
That is funny for sure. 😛 Sorry!

I submitted a orphan request.

**Comment by dglava** [comment]
The [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=openbox-arc-git) has an email address. You should email the maintainer first and ask if he can change it. The orphan request might not go through without that and the package being flagged out-of-that (at least that's what I read on the Arch Wiki and from personal experience).

**Comment by Brottweiler** [comment]
His [user page](https://aur.archlinux.org/account/patlux) actually has an email that differs, we can email both.

**Comment by patlux** [comment]
I removed the dependency. [openbox-arc-git](https://aur.archlinux.org/packages/openbox-arc-git/).

@dglava: Sorry, I didn't see the comment until now (or I forgot it).
