### ISSUE TITLE
[Suggestion] Adding in to official package

### ISSUE THREAD

**Issue by ghost** [dglava/arc-openbox#8]
Hello

First, thank you for this great work. Have you considered to contact original arc theme owner and add your openbox support in to their original repository?

**Comment by dglava** [comment]
The [original](https://github.com/horst3180/arc-theme) repository for the Arc theme hasn't seen activity in a long time and there's an open issue on it asking to consider merging it into the repository.

However, there is a fork of the theme which is continuing with improvements and fixes to the theme. It can be found [here](https://github.com/NicoHood/arc-theme). There is an [open request](https://github.com/NicoHood/arc-theme/pull/38) waiting to be merged which adds the Openbox theme. I guess it will get merged soon.
